### ISSUE TITLE
Document on a quickstart guide for Raspberry Pi Pico

### ISSUE THREAD

**Issue by stevefan1999-personal** [rust-embedded/cortex-m-quickstart#105]
https://www.raspberrypi.org/products/raspberry-pi-pico/

> Designed by Raspberry Pi, RP2040 features a **dual-core Arm Cortex-M0+** processor with 264KB internal RAM and support for up to 16MB of off-chip Flash. A wide range of flexible I/O options includes I2C, SPI, and — uniquely — Programmable I/O (PIO). These support endless possible applications for this small and affordable package.

**Comment by jonas-schievink** [comment]
The quickstart repo is device-agnostic, someone just has to create a HAL for that chip
