### ISSUE TITLE
cargo generate error

### ISSUE THREAD

**Issue by Zhonghui-Gao** [rust-embedded/cortex-m-quickstart#123]
![image](https://github.com/rust-embedded/cortex-m-quickstart/assets/61256021/882da195-3439-435c-bbd9-abb86cbb7e36)

how to solve 

but use git clone 
![image](https://github.com/rust-embedded/cortex-m-quickstart/assets/61256021/50bd5e01-88e5-4168-ae8c-aa8b3140c6c2)

Thx

**Comment by newAM** [comment]
I tried this out, it works for me.  Can you provide more information to help debug?

* What does `cargo generate --version` show?
* Can you translate the text after "failed to receive response"?
* Does `git clone` with the `https://` url work?

**Comment by Zhonghui-Gao** [comment]
thx！ just now I try this again to find error  but I find this no error. 
![image](https://github.com/rust-embedded/cortex-m-quickstart/assets/61256021/4b3f1834-c052-45f3-b355-ac2699bec1e4)

Maybe I reboot my computer just now. 

Finally, thank you very much for your help

**Comment by newAM** [comment]
I am glad it worked for you!  I'm going to close the issue since this appears to be resolved, feel free to reopen it!
