### ISSUE TITLE
Release build crashes

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/cortex-m-quickstart#50]
If I build this project with `--release` for `thumbv7em-none-eabi`, I end up in the Hardfault handler.

If I add an `asm::nop();` to the `loop { }` in `main`, it works fine. It's fine as a debug either with or without the `asm::nop()`.

I'm using a TM4C129 Launchpad, but haven't extern'd in a chip crate yet. I've attached the generated assembly.

[test_app.txt](https://github.com/rust-embedded/cortex-m-quickstart/files/2438160/test_app.txt)

**Comment by jonas-schievink** [comment]
This is likely to be caused by https://github.com/rust-lang/rust/issues/28728
