### ISSUE TITLE
Feature request: Confusing task names

### ISSUE THREAD

**Issue by bradleyharden** [rust-embedded/cortex-m-quickstart#99]
Hi,

I didn't have much experience with VSCode before using it with Rust. I was working with Cortex-Debug and the `preLaunchTask` field. The current Rust task names look like shell commands. Because of that, I assumed I could change the `preLaunchTask` string to a different shell command and it would work. I only realized later that the `preLaunchTask` string is actually a task name, and that the task names just happen to look like shell commands.

I think this is misleading and probably a source of confusion for others who are not familiar with VSCode tasks. Can I suggest changing the names to something that doesn't look like a shell command?

**Comment by rubberduck203** [comment]
I’m open to suggestions if you have better names in mind. 

I assume you’re talking about these labels?

https://github.com/rust-embedded/cortex-m-quickstart/blob/3cbcb9956acd638c0fb864937770f51d663fba6f/.vscode/tasks.json#L12

**Comment by bradleyharden** [comment]
@rubberduck203, yes that's what I'm talking about. I didn't have anything specific in mind. I just want something that looks like a label rather than a shell command. Maybe `Cargo - Build` and `Cargo - Build (release)`, or something like that? It's also not that big of a deal. I figured it out. It was just a bit confusing.

**Comment by rubberduck203** [comment]
How about the following?

- Cargo Build (debug)
- Cargo Build (release)
- Cargo Build Examples (debug)
- Cargo Build Examples (release)
- Cargo Clean

**Comment by bradleyharden** [comment]
Those look good to me.

There's no rush. I'll also try to get around to it soon, but you might beat me. Thanks for considering the change.

**Comment by rubberduck203** [comment]
@bradleyharden PR is open. Just need to wait for a maintainer now.
Thanks for bringing it to my attention.

**Comment by bradleyharden** [comment]
Thanks @rubberduck203!
